FROM maven:3.9.6-eclipse-temurin-21 AS common-build

WORKDIR /app
COPY ./ansh-common ./ansh-common

WORKDIR /app/ansh-common
RUN mvn clean install

FROM gradle:8.5-jdk21 AS gradle-build

WORKDIR /app

COPY ./ansh-stats-service/. .

COPY --from=common-build /root/.m2 /root/.m2

RUN gradle build

FROM eclipse-temurin:21-jdk

WORKDIR /app
COPY --from=gradle-build /app/build/libs/ansh-stats-service.jar ansh-stats-service-1.0.jar

ENTRYPOINT ["java", "-jar", "ansh-stats-service-1.0.jar"]
